# 端口配置
server:
  port: 8080
spring:
  # 数据源配置 使用druid数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    #SQL脚本导入
    #schema: classpath:/import.sql
    #sql-script-encoding: utf-8

  # jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # freemarker配置
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size:
  mail:
    host: smtp.exmail.qq.com
    username: i@ryanc.cc
    password: Wangdashen666
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # TODO config this ehcache
  cache:
    ehcache:
      config: ehcache.xml
# 设置日志输出路径
logging:
  file: ./logs/log.log



